name: Build Distribution

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install mpy-cross
      run: pip install mpy-cross

    - name: Make gendist.sh executable
      run: chmod +x gendist.sh

    - name: Run gendist.sh
      run: ./gendist.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
